# Default values for logging-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
common:
  name: logging
flow:
  filters:
  # This removes dots from log keys and converts them to underscores, improving compatibility with Elasticsearch
#  - dedot:
#      de_dot_separator: "-"
#      de_dot_nested: true
#    # This references an ClusterOutput CR
#    # exclude any drop/trace level message
#  - grep:
#      exclude:
#      - key: message
#        pattern: '/(?:debug|DEBUG|trace|TRACE)/'

  exclude: {}
  select:
    namespaces: [] 
output:
  kafka:
    brokers: 
    buffer:
      chunk_limit_size: 2M
      flush_interval: 10s
      flush_thread_count: 4
      tags: topic
      total_limit_size: 10G
    default_topic:  # this is the CDI topic youre sending to
  secrets:
    tls:
      name: 
      cert: tls.crt
      cert_key: tls.key